#!/bin/sh

PORT=`config-get tcp-port`
GREETING=`config-get greeting`

open-port $PORT/TCP

cat > `dirname $0`/../server/config.json <<EOF
{
    "port": $PORT,
    "greeting": "$GREETING"
}
EOF

cd `dirname $0`/../server/
npm install

exec `dirname $0`/start
