#!/bin/bash

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq nodejs daemon

cat > /home/ubuntu/main.js <<EOF
var http = require('http');
var fs = require('fs');
var index = fs.readFileSync('index.html');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.end(index);
}).listen(JSON.parse(fs.readFileSync("config.json"))['port']);
EOF
